version: "3"
services:
  postgres:
    restart: always
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ideahunt
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
  webserver:
    build: ./ideahunt
    depends_on:
      - postgres
    volumes:
      - ./ideahunt:/ideahunt
    ports:
      - "5050:5000"
    env_file:
      - ./ideahunt/.env
    stdin_open: true
    tty: true
    restart: always
    environment:
      PORT: 5000
      FLASK_APP: api.py
