"""Add basic Follow model

Revision ID: 8e53e7b1798e
Revises: d5753451be49
Create Date: 2021-02-16 04:34:31.455823

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e53e7b1798e"
down_revision = "d5753451be49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follow",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("followee_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "followee_id"),
    )
    op.create_index("followee_follower", "follow", ["followee_id", "user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("followee_follower", table_name="follow")
    op.drop_table("follow")
    # ### end Alembic commands ###
